const types = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAIL: "ADD_TO_CART_FAIL",
  REMOVE_FROM_CART_REQUEST: "REMOVE_FROM_CART_REQUEST",
  REMOVE_ALL_FROM_CART_REQUEST: "REMOVE_ALL_FROM_CART_REQUEST",
};

export default types;
