const types = {
  ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_FAIL: "ORDER_CREATE_FAIL",
  ORDER_CREATE_RESET: "ORDER_CREATE_RESET",
  ORDER_FETCH_REQUEST: "ORDER_FETCH_REQUEST",
  ORDER_FETCH_SUCCESS: "ORDER_FETCH_SUCCESS",
  ORDER_FETCH_FAIL: "ORDER_FETCH_FAIL",
  ORDER_PAY_REQUEST: "ORDER_PAY_REQUEST",
  ORDER_PAY_SUCCESS: "ORDER_PAY_SUCCESS",
  ORDER_PAY_FAIL: "ORDER_PAY_FAIL",
  ORDER_PAY_RESET: "ORDER_PAY_RESET",
};

export default types;
