import bCrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Joe",
      email: "joe@gmail.com",
      password: bCrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Lodzia",
      email: "lodzia@gmail.com",
      password: bCrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      _id: "1",
      name: "Nike slim shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 1.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 34,
      sellerId: 1,
    },
    {
      _id: "2",
      name: "Adidas slim shirt",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 90,
      brand: "Adidas",
      rating: 3.0,
      numReviews: 0,
      description: "high quality product",
      countInStock: 7,
      sellerId: 3,
    },
    {
      _id: "3",
      name: "Ralph free shirt",
      category: "shirts",
      image: "/images/p3.jpg",
      price: 250,
      brand: "Ralph Lauren",
      rating: 4.5,
      numReviews: 5,
      description: "high quality product",
      countInStock: 4,
      sellerId: 2,
    },
    {
      _id: "4",
      name: "Wrangler white pants",
      category: "pants",
      image: "/images/p4.jpg",
      price: 110,
      brand: "Wrangler",
      rating: 4.5,
      numReviews: 7,
      description: "high quality product",
      countInStock: 7,
      sellerId: 3,
    },
    {
      _id: "5",
      name: "Lee slim pants",
      category: "pants",
      image: "/images/p5.jpg",
      price: 90,
      brand: "Lee",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 1,
      sellerId: 4,
    },
    {
      _id: "6",
      name: "Nike elegant pants",
      category: "pants",
      image: "/images/p6.jpg",
      price: 70,
      brand: "Nike",
      rating: 5.0,
      numReviews: 12,
      description: "high quality product",
      countInStock: 0,
      sellerId: 2,
    },
  ],
  sellers: [
    {
      _id: 1,
      name: "Adam",
      rating: 2.5,
      numReviews: 0,
    },
    {
      _id: 2,
      name: "Niko",
      rating: 4.0,
      numReviews: 7,
    },
    {
      _id: 3,
      name: "Gosia",
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: 4,
      name: "Jarek",
      rating: 5.0,
      numReviews: 24,
    },
  ],
};

export default data;
