const types = {
  USER_SIGNIN_REQUEST: "USER_SIGNIN_REQUEST",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAIL: "USER_SIGNIN_FAIL",
  USER_SIGNOUT: "USER_SIGNOUT",
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
  USER_REGISTER_SET_INFO: "USER_SET_INFO",
  USER_FETCH_REQUEST: "USER_FETCH_REQUEST",
  USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS",
  USER_FETCH_FAIL: "USER_FETCH_FAIL",
};

export default types;
